---
title: "Water Temperature Prediction"
subtitle: "Day of Year and Depth XGBoost Model"
author: "Gregory Harrison, Claire Oberg"
date: "Nov 28, 2022"
output:
  pdf_document:
    highlight: haddock
keep_tex: no
number_sections: no
html_document:
  df_print: paged
geometry: margin = 0.5in
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
editor_options:
  chunk_output_type: console
documentclass: article
urlcolor: blue
---
  

```{r setup, include=FALSE}
# This is the setup chunk
#  Here you can set global options for the entire document

# Load libraries 
library(knitr)
library(dplyr)
library(xgboost)

# Although you can call functions from a library using the following notation
#  without loading the entire library.
knitr::opts_chunk$set(echo = TRUE, 
                      comment = NA, # Required
                      fig.path = "./figures/",  # Store all figures here in relative path (make the folder first)
                      fig.align = "center",
                      fig.width = 7,
                      fig.height = 7,
                      message = FALSE, # Turn off load messages
                      warning = FALSE # Turn off warnings
                      )

```


Read in Current Data from Lake Sunapee

```{r}

raw <- readr::read_csv("https://s3.flare-forecast.org/targets/sunp/sunp-targets-insitu.csv")
#raw <- readr::read_csv("sunp-targets-insitu.csv")

```

Convert Data to Dataframe

```{r}
# Convert to Dataframe
df = data.frame(raw)

# Generate year and day of year from the date column
df[['year']] <- strptime(df[['date']], format = "%Y-%m-%d")$year + 1900
df[['dayofyear']] <- as.numeric( format(df[['date']], '%j'))

# Filter data according to our assumptions being:
# only calculating at noon
# years during and after 2011 and not including 2015 and 2017 for low amounts of data
# Day of year range only between 162 and 278 
df <- df %>%
  filter(hour == 12) %>%
  filter(year >= 2011) %>%
  filter(year != 2017) %>%
  filter(year != 2015) %>%
  filter(dayofyear >= 162) %>%
  filter(dayofyear <= 278) 


#Remove the date, variable, and hour columns from our dataframe
df$date = NULL
df$variable = NULL
df$hour = NULL
```

Separate Training and Testing Sets

```{r}
# Separate our data into training (all years but 2013 and 2022) and 
# testings (years 2013 and 2022)
waterTrain = df[df$year != 2013 & df$year != 2022, ]
waterTest = df[df$year == 2013 | df$year == 2022, ]

# Drop Columns with NA's in them 
waterTrain = na.omit(waterTrain)
waterTest = na.omit(waterTest)
tempWater = waterTrain
```

Convert Training and Testing set for XGBoost

```{r}
# Remove the year columns now that we've used them to seperate the date
waterTrain$year = NULL
waterTest$year = NULL

# Generate our labels as the current water temperature
train.label = waterTrain$value
test.label = waterTest$value

# Remove the temperature values from the input data 
waterTrain$value = NULL
waterTest$value = NULL

# Convert the input data to a matrix for xgboost
train.data = as.matrix(waterTrain)
test.data = as.matrix(waterTest)
```

Train Model

```{r}
# Generate Training Input for XGBoost
dtrain<-xgb.DMatrix(data = train.data, label = train.label)
# Train our model
bst <- xgboost(data = dtrain, max.depth = 10, eta = 1, nthread = 2, nrounds = 20, verbose = 1)
# Product Predictions for our Testing Dataset
pred <- predict(bst, test.data)
# Calculate Mean Absolute Error 
mean(abs(pred-test.label))
```

See how the model performs on the original training data. 

```{r}
predTrain <- predict(bst, train.data)
mean(abs(predTrain-train.label))
```

Generate Some Graph of our data
Rename test.label observed 
```{r}
# Plot of Predicted vs. Actual Values
plot(pred, test.label)
abline(0,1)
```

```{r}
# Plot of Predicted vs. Day of Year
plot(pred, test.data[,2])
```

```{r}
# Summary of Error
summary(pred-test.label)
```

```{r}
# Histogram of Error
den<-density(pred-test.label)
plot(den)
```

```{r}
hist(pred-test.label)
```

```{r}
sqrt(mean((pred-test.label)^2))
```

